name: Test
on:
 workflow_dispatch:
jobs:
 notify-start:
   runs-on: ubuntu-latest
   steps:
     - name: send mail
       uses: dawidd6/action-send-mail@v3       
       with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USER}}
        password: ${{ secrets.EMAIL_PASS}}
        subject: "pipline trigger"
        to: saikiranyerraji000@gmail.com
        from: GitHub Actions
        body: "Automation testing" 
        secure: false        
        
          
